### ISSUE TITLE
Request quota exhaustion

### ISSUE THREAD

**Issue by yrashk** [nektro/actions-setup-zigmod#6]
Saw my CI run fail with:

```
Request quota exhausted for request GET /repos/{owner}/{repo}/releases
Retrying after 830 seconds!
Request quota exhausted for request GET /repos/{owner}/{repo}/releases
Retrying after 0 seconds!
Request quota exhausted for request GET /repos/{owner}/{repo}/releases
Retrying after 0 seconds!
```

Maybe we can add a version specification to the config so that there would be no need to list releases?

**Comment by yrashk** [comment]
See #7

**Comment by kivikakk** [comment]
I'm hitting this a lot, too: https://github.com/kivikakk/koino/runs/4909802388?check_suite_focus=true

**Comment by nektro** [comment]
will add to the docs, but this should fix it
```yml
      - uses: nektro/actions-setup-zigmod@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
